services:
  - type: web
    name: bakeryapp-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false # You need to set this manually in Render dashboard
      - key: PORT
        fromService:
          type: web
          name: bakeryapp-backend
          property: port
      - key: RAZORPAY_KEY_ID
        value: rzp_test_RcMmnysFvW4rZD
      - key: RAZORPAY_KEY_SECRET
        value: wKfBAymLddrv1B3WW1RVG1E0
